[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0B6E69"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F6F5"
textColor = "#16302E"
font = "sans serif"
